// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://batbacvcylhyblfhjtjo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhdGJhY3ZjeWxoeWJsZmhqdGpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNDk2MjAsImV4cCI6MjA2ODkyNTYyMH0.18Z97pz12Pxpb1Fbd5jn-sTk8UVXRFdQPVs7mGbcuQU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});